/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface SchemaField {
    

    name?: string;

    type?: SchemaField.TypeEnum;

    unique?: boolean;

    descriptiveName?: string;

    description?: string;

    category?: string;
}
export namespace SchemaField {

    export enum TypeEnum { 
        STRING = <any> 'STRING',
        INTEGER = <any> 'INTEGER',
        DECIMAL = <any> 'DECIMAL',
        DOUBLE = <any> 'DOUBLE',
        LONG = <any> 'LONG',
        BOOLEAN = <any> 'BOOLEAN',
        DATE = <any> 'DATE',
        TIME = <any> 'TIME',
        TIMESTAMP = <any> 'TIMESTAMP',
        BINARY = <any> 'BINARY',
        ARRAY_STRING = <any> 'ARRAY_STRING',
        ARRAY_INTEGER = <any> 'ARRAY_INTEGER',
        ARRAY_DECIMAL = <any> 'ARRAY_DECIMAL',
        ARRAY_DOUBLE = <any> 'ARRAY_DOUBLE',
        ARRAY_LONG = <any> 'ARRAY_LONG',
        ARRAY_BOOLEAN = <any> 'ARRAY_BOOLEAN',
        ARRAY_DATE = <any> 'ARRAY_DATE',
        ARRAY_TIME = <any> 'ARRAY_TIME',
        ARRAY_TIMESTAMP = <any> 'ARRAY_TIMESTAMP',
        ARRAY_BINARY = <any> 'ARRAY_BINARY',
        MAP_STRING = <any> 'MAP_STRING',
        MAP_INTEGER = <any> 'MAP_INTEGER',
        MAP_DECIMAL = <any> 'MAP_DECIMAL',
        MAP_DOUBLE = <any> 'MAP_DOUBLE',
        MAP_LONG = <any> 'MAP_LONG',
        MAP_BOOLEAN = <any> 'MAP_BOOLEAN',
        MAP_DATE = <any> 'MAP_DATE',
        MAP_TIME = <any> 'MAP_TIME',
        MAP_TIMESTAMP = <any> 'MAP_TIMESTAMP',
        MAP_BINARY = <any> 'MAP_BINARY',
    }
}
